Fix shell scripts for shellcheck

diff --git a/home/.githooks/pre-commit b/home/.githooks/pre-commit
--- a/home/.githooks/pre-commit
+++ b/home/.githooks/pre-commit
@@ -1,12 +1,12 @@
 #!/bin/bash
 
-while read -r hook; do
-    bash "$(dirname "$0")/pre-commit.d/$hook"
+for hook in "$(dirname "$0")"/pre-commit.d/*; do
+    bash "${hook}"
     RESULT=$?
-    if [ $RESULT != 0 ]; then
-        echo "pre-commit.d/$hook returned non-zero: $RESULT, abort commit"
-        exit $RESULT
+    if [[ "${RESULT}" != 0 ]]; then
+        echo "$(basename "${hook}") returned non-zero: ${RESULT}, abort commit"
+        exit "${RESULT}"
     fi
-done <<< "$(ls $(dirname "$0")/pre-commit.d)"
+done
 
 exit 0
diff --git a/home/.githooks/pre-push b/home/.githooks/pre-push
--- a/home/.githooks/pre-push
+++ b/home/.githooks/pre-push
@@ -1,12 +1,12 @@
 #!/bin/bash
 
-while read -r hook; do
-    bash "$(dirname "$0")/pre-push.d/$hook"
+for hook in "$(dirname "$0")"/pre-push.d/*; do
+    bash "${hook}"
     RESULT=$?
-    if [ $RESULT != 0 ]; then
-        echo "pre-push.d/$hook returned non-zero: $RESULT, abort commit"
-        exit $RESULT
+    if [[ "${RESULT}" != 0 ]]; then
+        echo "$(basename "${hook}") returned non-zero: ${RESULT}, abort commit"
+        exit "${RESULT}"
     fi
-done <<< "$(ls $(dirname "$0")/pre-push.d)"
+done
 
 exit 0
